Disable Win/Mac autobuild for testing

diff --git a/.github/workflows/build-usbsid-on-push.yml b/.github/workflows/build-usbsid-on-push.yml
--- a/.github/workflows/build-usbsid-on-push.yml
+++ b/.github/workflows/build-usbsid-on-push.yml
@@ -119,116 +119,10 @@ jobs:
             core.setOutput('release_id', createReleaseResponse.data.id);
             core.setOutput('upload_url', createReleaseResponse.data.upload_url);
 
-  build_win:
-      name: Build
-      needs: [create_release]
-      runs-on: windows-latest
-      strategy:
-        fail-fast: false
-        matrix:
-          arch:
-          - { msystem: MINGW64, arch: x86_64, prefix: mingw64 }
-            #- { msystem: MINGW32, arch: i686,   prefix: mingw32 }
-      steps:
-        - run: git config --global core.autocrlf input
-          shell: bash
-
-        - name: Checkout Source
-          if: env.exiting1 != 'true'
-          uses: actions/checkout@v4
-
-        - name: Install SDL2 Dependencies if Applicable
-          uses: msys2/setup-msys2@v2
-          with:
-            msystem: ${{ matrix.arch.msystem }}
-            update: true
-            install: >-
-              autotools
-              base-devel
-              git
-              mingw-w64-${{ matrix.arch.arch }}-SDL
-              mingw-w64-${{ matrix.arch.arch }}-SDL_image
-              mingw-w64-${{ matrix.arch.arch }}-SDL2
-              mingw-w64-${{ matrix.arch.arch }}-SDL2_image
-              mingw-w64-${{ matrix.arch.arch }}-curl
-              mingw-w64-${{ matrix.arch.arch }}-docbook-xml
-              mingw-w64-${{ matrix.arch.arch }}-docbook-xsl
-              mingw-w64-${{ matrix.arch.arch }}-flac
-              mingw-w64-${{ matrix.arch.arch }}-giflib
-              mingw-w64-${{ matrix.arch.arch }}-glew
-              mingw-w64-${{ matrix.arch.arch }}-icoutils
-              mingw-w64-${{ matrix.arch.arch }}-lame
-              mingw-w64-${{ matrix.arch.arch }}-libpcap
-              mingw-w64-${{ matrix.arch.arch }}-libvorbis
-              mingw-w64-${{ matrix.arch.arch }}-mpg123
-              mingw-w64-${{ matrix.arch.arch }}-ntldd
-              mingw-w64-${{ matrix.arch.arch }}-pkg-config
-              mingw-w64-${{ matrix.arch.arch }}-portaudio
-              mingw-w64-${{ matrix.arch.arch }}-toolchain
-              mingw-w64-${{ matrix.arch.arch }}-xa65
-              mingw-w64-${{ matrix.arch.arch }}-libusb
-              p7zip
-              subversion
-              unzip
-              xmlto
-              zip
-
-        - name: Build
-          id: build
-          shell: msys2 {0}
-          run: |
-            mkdir -p win32
-            cd src
-            cp makefile.win makefile
-            cd bme
-            cp makefile.win makefile
-            make -j2 -s --no-print-directory
-            cd ../
-            make -j2 -s --no-print-directory
-
-        - name: Zip files
-          id: make_zip
-          working-directory: ${{github.workspace}}
-          shell: bash
-          run: |
-            mkdir gt2ultra-win
-            cp -av win32/* gt2ultra-win32/
-            zip -r gt2ultra-win-taggedbuild-${{ steps.vars.outputs.tag }}.zip gt2ultra-win32/
-
-        - name: Upload Zip
-          id: upload-zip
-          uses: actions/github-script@v7
-          env:
-            UPLOAD_URL: ${{ needs.create_release.outputs.upload_url }}
-            ASSET_PATH: ${{github.workspace}}/gt2ultra-win32/gt2ultra-win-taggedbuild-${{ steps.vars.outputs.tag }}.zip
-            ASSET_NAME: gt2ultra-win-taggedbuild-${{ steps.vars.outputs.tag }}.zip
-            ASSET_CONTENT_TYPE: application/zip
-          with:
-            github-token: ${{secrets.GITHUB_TOKEN}}
-            retries: 3
-            script: |
-              const fs = require('fs');
-              const { UPLOAD_URL, ASSET_PATH, ASSET_NAME, ASSET_CONTENT_TYPE } = process.env;
-              const uploadAssetResponse = await github.rest.repos.uploadReleaseAsset({
-                url: UPLOAD_URL,
-                headers: {
-                  'content-type': ASSET_CONTENT_TYPE,
-                  'content-length': fs.statSync(ASSET_PATH).size
-                },
-                name: ASSET_NAME,
-                data: fs.readFileSync(ASSET_PATH)
-              });
-
   build_lin:
     name: Build Linux Package
     needs: [create_release]
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-          ui: [ { name: 'SDL2',
-                  deps: 'libsdl1.2-dev libsdl-image1.2-dev libsdl2-dev libsdl2-image-dev' },
-              ]
     steps:
       - shell: bash
         run: git config --global core.autocrlf input
@@ -267,8 +161,14 @@ jobs:
                               texinfo \
                               texlive-fonts-recommended \
                               texlive-latex-extra \
-                              xa65
-          sudo apt install -y ${{ matrix.ui.deps }}
+                              xa65 \
+                              libsdl-image1.2-dev \
+                              libsdl1.2-dev \
+                              libsdl1.2debian \
+                              libsdl2-2.0-0 \
+                              libsdl2-dev \
+                              libsdl2-image-2.0-0 \
+                              libsdl2-image-dev
 
       - name: Build
         shell: bash
@@ -276,10 +176,6 @@ jobs:
           mkdir -p linux
           cd src
           cp makefile.lin makefile
-          cd bme
-          cp makefile.lin makefile
-          make -j2 -s --no-print-directory
-          cd ../
           make -j2 -s --no-print-directory
 
       - name: Zip files
@@ -315,92 +211,193 @@ jobs:
               data: fs.readFileSync(ASSET_PATH)
             });
 
-  build_mac:
-    name: Build MacOs Package
-    needs: [create_release]
-    runs-on: macos-latest
-    strategy:
-      fail-fast: false
-      matrix:
-          ui: [ { name: 'SDL2',
-                  deps: 'sdl sdl12-compat sdl2 sdl2_image' },
-              ]
-    steps:
-      - name: Checkout Source
-        uses: actions/checkout@v4
+  # build_win:
+  #     name: Build
+  #     needs: [create_release]
+  #     runs-on: windows-latest
+  #     strategy:
+  #       fail-fast: false
+  #       matrix:
+  #         arch:
+  #         - { msystem: MINGW64, arch: x86_64, prefix: mingw64 }
+  #           #- { msystem: MINGW32, arch: i686,   prefix: mingw32 }
+  #     steps:
+  #       - run: git config --global core.autocrlf input
+  #         shell: bash
 
-      - name: deps [macOS]
-        if: runner.os == 'macOS'
-        run: |
-          export HOMEBREW_NO_INSTALL_CLEANUP=1
-          brew update
-          brew upgrade || true
-          brew uninstall --ignore-dependencies --force pkg-config@0.29.2
-          brew install \
-            dos2unix \
-            autoconf \
-            automake \
-            libtool \
-            pkgconf \
-            coreutils \
-            gnu-sed \
-            libgcrypt \
-            xa \
-            librsvg \
-            adwaita-icon-theme \
-            glew \
-            libusb \
-            libusb-compat \
-            ${{ matrix.ui.deps }}
-      - name: Build
-        run: |
-          mkdir -p macos
-          cd src
-          cp makefile.mac makefile
-          cd bme
-          cp makefile.mac makefile
-          make -j2 -s --no-print-directory
-          cd ../
-          make -j2 -s --no-print-directory
+  #       - name: Checkout Source
+  #         if: env.exiting1 != 'true'
+  #         uses: actions/checkout@v4
 
-      - name: Zip files
-        id: make_zip
-        working-directory: ${{github.workspace}}
-        shell: bash
-        run: |
-          mkdir gt2ultra-macos
-          cp -av macos/* gt2ultra-macos/
-          tar cvzf gt2ultra-macos-taggedbuild-${{ steps.vars.outputs.tag }}.tgz -C gt2ultra-macos .
-          pwd
-          ls -l
+  #       - name: Install SDL2 Dependencies if Applicable
+  #         uses: msys2/setup-msys2@v2
+  #         with:
+  #           msystem: ${{ matrix.arch.msystem }}
+  #           update: true
+  #           install: >-
+  #             autotools
+  #             base-devel
+  #             git
+  #             mingw-w64-${{ matrix.arch.arch }}-SDL
+  #             mingw-w64-${{ matrix.arch.arch }}-SDL_image
+  #             mingw-w64-${{ matrix.arch.arch }}-SDL2
+  #             mingw-w64-${{ matrix.arch.arch }}-SDL2_image
+  #             mingw-w64-${{ matrix.arch.arch }}-curl
+  #             mingw-w64-${{ matrix.arch.arch }}-docbook-xml
+  #             mingw-w64-${{ matrix.arch.arch }}-docbook-xsl
+  #             mingw-w64-${{ matrix.arch.arch }}-flac
+  #             mingw-w64-${{ matrix.arch.arch }}-giflib
+  #             mingw-w64-${{ matrix.arch.arch }}-glew
+  #             mingw-w64-${{ matrix.arch.arch }}-icoutils
+  #             mingw-w64-${{ matrix.arch.arch }}-lame
+  #             mingw-w64-${{ matrix.arch.arch }}-libpcap
+  #             mingw-w64-${{ matrix.arch.arch }}-libvorbis
+  #             mingw-w64-${{ matrix.arch.arch }}-mpg123
+  #             mingw-w64-${{ matrix.arch.arch }}-ntldd
+  #             mingw-w64-${{ matrix.arch.arch }}-pkg-config
+  #             mingw-w64-${{ matrix.arch.arch }}-portaudio
+  #             mingw-w64-${{ matrix.arch.arch }}-toolchain
+  #             mingw-w64-${{ matrix.arch.arch }}-xa65
+  #             mingw-w64-${{ matrix.arch.arch }}-libusb
+  #             p7zip
+  #             subversion
+  #             unzip
+  #             xmlto
+  #             zip
 
-      - name: Upload zip
-        id: upload_macoszip
-        uses: actions/github-script@v7
-        env:
-          UPLOAD_URL: ${{ needs.create_release.outputs.upload_url }}
-          ASSET_PATH: ${{github.workspace}}/gt2ultra-macos-taggedbuild-${{ steps.vars.outputs.tag }}.tgz
-          ASSET_NAME: gt2ultra-macos-taggedbuild-${{ steps.vars.outputs.tag }}.tgz
-          ASSET_CONTENT_TYPE: application/vnd.debian.binary-package
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          retries: 3
-          script: |
-            const fs = require('fs');
-            const { UPLOAD_URL, ASSET_PATH, ASSET_NAME, ASSET_CONTENT_TYPE } = process.env;
-            const uploadAssetResponse = await github.rest.repos.uploadReleaseAsset({
-              url: UPLOAD_URL,
-              headers: {
-                'content-type': ASSET_CONTENT_TYPE,
-                'content-length': fs.statSync(ASSET_PATH).size
-              },
-              name: ASSET_NAME,
-              data: fs.readFileSync(ASSET_PATH)
-            });
+  #       - name: Build
+  #         id: build
+  #         shell: msys2 {0}
+  #         run: |
+  #           mkdir -p win32
+  #           cd src
+  #           cp makefile.win makefile
+  #           cd bme
+  #           cp makefile.win makefile
+  #           make -j2 -s --no-print-directory
+  #           cd ../
+  #           make -j2 -s --no-print-directory
+
+  #       - name: Zip files
+  #         id: make_zip
+  #         working-directory: ${{github.workspace}}
+  #         shell: bash
+  #         run: |
+  #           mkdir gt2ultra-win
+  #           cp -av win32/* gt2ultra-win32/
+  #           zip -r gt2ultra-win-taggedbuild-${{ steps.vars.outputs.tag }}.zip gt2ultra-win32/
+
+  #       - name: Upload Zip
+  #         id: upload-zip
+  #         uses: actions/github-script@v7
+  #         env:
+  #           UPLOAD_URL: ${{ needs.create_release.outputs.upload_url }}
+  #           ASSET_PATH: ${{github.workspace}}/gt2ultra-win32/gt2ultra-win-taggedbuild-${{ steps.vars.outputs.tag }}.zip
+  #           ASSET_NAME: gt2ultra-win-taggedbuild-${{ steps.vars.outputs.tag }}.zip
+  #           ASSET_CONTENT_TYPE: application/zip
+  #         with:
+  #           github-token: ${{secrets.GITHUB_TOKEN}}
+  #           retries: 3
+  #           script: |
+  #             const fs = require('fs');
+  #             const { UPLOAD_URL, ASSET_PATH, ASSET_NAME, ASSET_CONTENT_TYPE } = process.env;
+  #             const uploadAssetResponse = await github.rest.repos.uploadReleaseAsset({
+  #               url: UPLOAD_URL,
+  #               headers: {
+  #                 'content-type': ASSET_CONTENT_TYPE,
+  #                 'content-length': fs.statSync(ASSET_PATH).size
+  #               },
+  #               name: ASSET_NAME,
+  #               data: fs.readFileSync(ASSET_PATH)
+  #             });
+
+  # build_mac:
+  #   name: Build MacOs Package
+  #   needs: [create_release]
+  #   runs-on: macos-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #         ui: [ { name: 'SDL2',
+  #                 deps: 'sdl sdl12-compat sdl2 sdl2_image' },
+  #             ]
+  #   steps:
+  #     - name: Checkout Source
+  #       uses: actions/checkout@v4
+
+  #     - name: deps [macOS]
+  #       if: runner.os == 'macOS'
+  #       run: |
+  #         export HOMEBREW_NO_INSTALL_CLEANUP=1
+  #         brew update
+  #         brew upgrade || true
+  #         brew uninstall --ignore-dependencies --force pkg-config@0.29.2
+  #         brew install \
+  #           dos2unix \
+  #           autoconf \
+  #           automake \
+  #           libtool \
+  #           pkgconf \
+  #           coreutils \
+  #           gnu-sed \
+  #           libgcrypt \
+  #           xa \
+  #           librsvg \
+  #           adwaita-icon-theme \
+  #           glew \
+  #           libusb \
+  #           libusb-compat \
+  #           ${{ matrix.ui.deps }}
+  #     - name: Build
+  #       run: |
+  #         mkdir -p macos
+  #         cd src
+  #         cp makefile.mac makefile
+  #         cd bme
+  #         cp makefile.mac makefile
+  #         make -j2 -s --no-print-directory
+  #         cd ../
+  #         make -j2 -s --no-print-directory
+
+  #     - name: Zip files
+  #       id: make_zip
+  #       working-directory: ${{github.workspace}}
+  #       shell: bash
+  #       run: |
+  #         mkdir gt2ultra-macos
+  #         cp -av macos/* gt2ultra-macos/
+  #         tar cvzf gt2ultra-macos-taggedbuild-${{ steps.vars.outputs.tag }}.tgz -C gt2ultra-macos .
+  #         pwd
+  #         ls -l
+
+  #     - name: Upload zip
+  #       id: upload_macoszip
+  #       uses: actions/github-script@v7
+  #       env:
+  #         UPLOAD_URL: ${{ needs.create_release.outputs.upload_url }}
+  #         ASSET_PATH: ${{github.workspace}}/gt2ultra-macos-taggedbuild-${{ steps.vars.outputs.tag }}.tgz
+  #         ASSET_NAME: gt2ultra-macos-taggedbuild-${{ steps.vars.outputs.tag }}.tgz
+  #         ASSET_CONTENT_TYPE: application/vnd.debian.binary-package
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         retries: 3
+  #         script: |
+  #           const fs = require('fs');
+  #           const { UPLOAD_URL, ASSET_PATH, ASSET_NAME, ASSET_CONTENT_TYPE } = process.env;
+  #           const uploadAssetResponse = await github.rest.repos.uploadReleaseAsset({
+  #             url: UPLOAD_URL,
+  #             headers: {
+  #               'content-type': ASSET_CONTENT_TYPE,
+  #               'content-length': fs.statSync(ASSET_PATH).size
+  #             },
+  #             name: ASSET_NAME,
+  #             data: fs.readFileSync(ASSET_PATH)
+  #           });
 
   publish_release:
     name: Publish Release
-    needs: [create_release, build_mac, build_win, build_lin]
+    # needs: [create_release, build_mac, build_win, build_lin]
+    needs: [create_release, build_lin]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/github-script@v7
